spring.jpa:
  hibernate.ddl-auto: none
  show-sql: true

spring.datasource:
  url: jdbc:postgresql://localhost:5432/flight_booking
  username: postgres
  password: postgres


server:
  port: 8082

jwt:
  secret: secret
  clockSkew: 10
  validFor: 36000

